### ISSUE TITLE
Running the docker container without "-it" does not work

### ISSUE THREAD

**Issue by FrederikP** [fangedhex/ecosurvivalserver#1]
Hi,

I tried to get this to work for an hour or so, until a friend of mine reversed the code to find out that it fails at a "Console.ReadLine()", because it returns null, when docker is not supplied with "-it".

This happens because the program looks for exit to be written. This will make the game stop and save. Probably they introduced it and then your docker run command did not work anymore and the NullPointer was thrown.

-t              : Allocate a pseudo-tty
-i              : Keep STDIN open even if not attached

This can still be combined with -d.

Maybe that can help you.

Cheers,
Frederik

**Comment by fangedhex** [comment]
Oh ! Thanks for information, I will look into it :)

**Comment by fangedhex** [comment]
Noted & Written on the README file as command to launch it :)
