### ISSUE TITLE
Need to find a way to auto update it

### ISSUE THREAD

**Issue by fangedhex** [fangedhex/ecosurvivalserver#2]
I need to find a way to auto update this repository when a new Eco Server version is out !

**Comment by zokradonh** [comment]
Here you have a nice XML document of all releases:
https://s3-us-west-2.amazonaws.com/eco-releases/
Writing a simple script that retrieves the newest release should not be a problem.

But how to trigger the Docker Hub build automatically?
I think of another extra script called by cronjob daily that watches the eco-releases/ url and calls a trigger endpoint on hub.docker.com.
This extra script should run on your server for example.

This is what I would do. Don't know if there are better ways.

**Comment by fangedhex** [comment]
Thanks for that link, I will look into it. I have some raspberry pi to use anyway if I need a simple script to trigger docker hub :)

**Comment by fangedhex** [comment]
In the meantime, I setup a system to let the user choose the version of Eco through an env variable, if the user doesn't set it, it will be set to 0.7.2.5-beta :)

**Comment by zokradonh** [comment]
Okay, downloading everything on startup is a rather brute force method xD

How do you manage the configs on your server? As far as I understand every start of the server will override any file in Configs folder with default files. This would delete my configs on my server since I also mounted the configs folder.

Btw, it is best practice to finish the apt-get RUN commands 
```
RUN apt-get update && \
apt-get install -y wget unzip \
&& rm -rf /var/cache/apt /var/lib/apt/lists
```
This gives you space.
Furthermore a little thing: place the new ENV command after the apt-get command (or any postion later). Building on docker hub doesn't matter but if someone builds this Dockerfile himself he can make use of caching layers. So changing eco version doesn't require redownloading/installing wget and unzip packages.

**Comment by fangedhex** [comment]
There is no configs inside the zip downloaded from AWS so it will not overwrite anything, it's the Eco Server itself that write configs if there are not configs there :p

For Dockerfile, I will update it with your recommandations, I'm starting to use Docker everyday now but I don't have a lot of practice in making Dockerfile ^^

**Comment by zokradonh** [comment]
Okay, I am new to eco server configuration.

This is what I have in my downloaded zip:
![image](https://user-images.githubusercontent.com/6594963/37874345-7c395918-302d-11e8-8223-eed6223e1249.png)

In my server setup I changed those files according to my needs.

**Comment by fangedhex** [comment]
Oh so now they are packaging up Configs files inside it.It wasn't like that before. I will do a quickfix, also I will setup Docker Hub to have latest and stable channel based on develop branch and master branch to not make anymore mistakes for production servers :)

**Comment by fangedhex** [comment]
I revert my change a bit : 
So it will now redo the download/unzip on build time, the small change is about a var that you can change when building (look at the README on develop branch)

Can you try to test it ? You need to git clone my repositories cause docker build doesn't handle git branch (it will download the master repository I think)

After testing, I will look into making a software to launch auto build of eco server version :p

**Comment by zokradonh** [comment]
I have looked further into the "XML Document" and saw that this is simply a public amazon bucket listing. So you can easily traverse the files with the aws cli. Last night it got me and I made a dockerfile using the aws cli to download the latest version.

I also published it on github:
https://github.com/ZokRadonh/ecogameserver

Do you want credit in License file?

I have also not solved the problem of auto build triggering yet.

**Comment by fangedhex** [comment]
For the credit, its up to you :)

For the auto building part, we need to run it on an host, I will try to see if my Docker Swarm of Raspberry PI can handle this :D

**Comment by fangedhex** [comment]
So I started a nodejs project in develop branch that it will check and build each Eco Server version : still need to check if the tag exists on docker hub through but the test are actually working for the moment (Some tags are already pushed into the hub right now)

EDIT : All versions have been uploaded to Docker Hub, if any image is not working, please tell me, they are all made from the same Dockerfile so it can have some bugs :(

**Comment by zokradonh** [comment]
Nice. Due to the fact that the results in the XMLDocument are truncated you may find this link useful:
https://s3-us-west-2.amazonaws.com/eco-releases/?prefix=EcoServer

Also you can directly connect to amazon via [aws-cli](http://aws.amazon.com/cli) for listing files and downloading.

**Comment by fangedhex** [comment]
I tried to find a npm package for using the cli but didn't find anything correct so I ended up with just a xml parser and it works as intended... I will still update the url to this one, it seems better :)

**Comment by fangedhex** [comment]
So for the moment, I'm testing the new system :)
