### ISSUE TITLE
Not able to build custom version

### ISSUE THREAD

**Issue by surcoufx83** [fangedhex/ecosurvivalserver#3]
Hi Fanged-Hex,

thank you for the effort setting up a working eco server container. It's working very good with the existing tags. Now I tried (my first time) building the container based on one of the new versions (7.4.x) of the game.
But the command as stated in the Repositories Readme can't be ran as expected. When building for game version 0.7.4.2-beta, it will always pull 0.7.2.5-beta. When forcing to build from develop-branch, the build command can't find the Dockerfile (the one that was moved to docker/EcoServer). As a workaround, I recreated the Dockerfile and it's working. But I lost your check against exitsing Tags.

Hope you can address this. 

Running as described in Readme (does not respect the ECO_VERSION ARG):
```
root@Server:/home/media2/docker# docker build -t mellhen/ecosurvivalserver:7.4.2 --build-arg ECO_VERSION=0.7.4.2-beta https://github.com/Fanged-Hex/EcoSurvivalServer.git
Sending build context to Docker daemon  60.93kB
Step 1/9 : FROM mono
 ---> fc9d64b6431f
Step 2/9 : ENV ECO_VERSION 0.7.2.5-beta
 ---> Using cache
 ---> a739488e3564
Step 3/9 : LABEL maintainer "Sylvain VISTE <viste.sylvain@gmail.com>"
 ---> Using cache
 ---> 42c5dbd2837a
Step 4/9 : RUN apt-get update && apt-get install -y wget unzip
 ---> Using cache
 ---> 2e332aa545bb
Step 5/9 : EXPOSE 2999/udp 3000 3001
 ---> Using cache
 ---> d978cb1a4970
Step 6/9 : WORKDIR /app
 ---> Using cache
 ---> d20e0a03b3c5
Step 7/9 : ADD bootstrap.sh /app/
 ---> Using cache
 ---> b44c3c937796
Step 8/9 : RUN chmod +x /app/bootstrap.sh
 ---> Using cache
 ---> 10bba5d82b62
Step 9/9 : CMD ["./bootstrap.sh"]
 ---> Using cache
 ---> 9408bb1ac53f
[Warning] One or more build-args [ECO_VERSION] were not consumed
Successfully built 9408bb1ac53f
Successfully tagged mellhen/ecosurvivalserver:7.4.2
```

Running with develop branch:
```
root@Server:/home/media2/docker# docker build -t mellhen/ecosurvivalserver:7.4.2 --build-arg ECO_VERSION=0.7.4.2-beta https://github.com/Fanged-Hex/EcoSurvivalServer.git#develop
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/docker-build-git792293181/Dockerfile: no such file or directory
```

**Comment by fangedhex** [comment]
That's because the develop branch is something I'm working on to auto build a image on eco release, but I still need to find some free time to work on this project to finish it up : 

1) Need to setup the project to run on cronjob so it runs once a day
2) I need to finish to setup my small server in my home to run it

If you can't wait, use the master branch, it will work I think (didn't test it). Actually I'm running by hand the program on my computer to push eco version on Docker Hub here : https://hub.docker.com/r/fangedhex/ecosurvivalserver/

**Comment by surcoufx83** [comment]
I wasn't sure about the current state. Thank you for your update.

**Comment by fangedhex** [comment]
Anyway, I will try to work on it today or tomorrow to finish my auto update system so it will auto publish new updates on Docker Hub :)
